# Generated by Django 5.2.4 on 2025-07-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_mail', models.CharField()),
                ('body_mail', models.TextField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['topic_mail', 'body_mail'],
            },
        ),
    ]
