# Generated by Django 5.2.4 on 2025-07-28 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userslist_delete_usersmodels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userslist',
            options={'ordering': ['owner', 'email_name'], 'permissions': [('can_view_for_list_user', 'Can view for list user')], 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
    ]
