# Generated by Django 5.2.4 on 2025-07-27 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(unique=True)),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField(blank=True, max_length=50, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'получатель рассылки',
                'verbose_name_plural': 'получатели рассылки',
                'ordering': ['email', 'full_name', 'comment'],
                'permissions': [('can_create_client', 'Can create client'), ('can_view_client', 'Can view client'), ('can_update_recipient', 'Can update recipient'), ('can_delete_recipient', 'Can delete recipient')],
            },
        ),
    ]
