# Generated by Django 5.2.4 on 2025-07-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(unique=True)),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['email', 'full_name', 'comment'],
            },
        ),
    ]
