# Generated by Django 5.2.4 on 2025-07-27 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipient',
            options={'ordering': ['email', 'full_name', 'comment'], 'permissions': [('can_create_client', 'Can create client'), ('can_view_client', 'Can view client'), ('can_update_recipient', 'Can update recipient'), ('can_delete_recipient', 'Can delete recipient'), ('can_view_for_manager', 'Can view for manager')], 'verbose_name': 'получатель рассылки', 'verbose_name_plural': 'получатели рассылки'},
        ),
    ]
