# Generated by Django 5.2.4 on 2025-07-27 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_recipient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipient',
            options={'ordering': ['email', 'full_name', 'comment'], 'permissions': [('can_view_for_manager', 'Can view for manager')], 'verbose_name': 'получатель рассылки', 'verbose_name_plural': 'получатели рассылки'},
        ),
    ]
