# Generated by Django 5.2.4 on 2025-07-28 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_recipient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipient',
            options={'ordering': ['email', 'full_name', 'comment'], 'verbose_name': 'получатель рассылки', 'verbose_name_plural': 'получатели рассылки'},
        ),
    ]
