# Generated by Django 5.2.4 on 2025-07-28 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_recipient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipient',
            options={'ordering': ['email', 'full_name', 'comment'], 'permissions': [('can_view_client_list', 'Can view client list')], 'verbose_name': 'получатель рассылки', 'verbose_name_plural': 'получатели рассылки'},
        ),
    ]
