# Generated by Django 5.2.4 on 2025-07-27 00:08

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('message', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_of_first_shipment', models.DateTimeField(auto_now_add=True)),
                ('end_dt_of_sending', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена')], default='Создана', max_length=100, verbose_name='статус')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.message')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(to='client.recipient')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'ordering': ['dt_of_first_shipment', 'end_dt_of_sending', 'status', 'message'],
            },
        ),
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_of_attempt', models.DateTimeField(default=datetime.datetime.now)),
                ('status_of_attempt', models.CharField(choices=[('Успешно', 'Успешно'), ('Не успешно', 'Не успешно')], default='Успешно', max_length=100, verbose_name='Статус попытки рассылки')),
                ('answer_server', models.TextField(blank=True, max_length=20, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailings.newsletter')),
            ],
            options={
                'verbose_name': 'попытка рассылки',
                'verbose_name_plural': 'попытки рассылки',
                'ordering': ['dt_of_attempt', 'status_of_attempt', 'answer_server', 'newsletter'],
                'permissions': [('can_create_mailings', 'Can create mailings'), ('can_view_mailings', 'Can view mailings'), ('can_update_mailings', 'Can update mailings'), ('can_delete_mailings', 'Can delete mailings')],
            },
        ),
    ]
