# Generated by Django 5.2.4 on 2025-07-19 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_of_first_shipment', models.DateTimeField(auto_now_add=True)),
                ('end_dt_of_sending', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена')], default='Создана', max_length=100, verbose_name='статус')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.message')),
                ('recipients', models.ManyToManyField(to='client.recipient')),
            ],
            options={
                'ordering': ['dt_of_first_shipment', 'end_dt_of_sending', 'status', 'message'],
            },
        ),
    ]
