# Generated by Django 5.2.4 on 2025-07-27 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingattempt',
            options={'ordering': ['dt_of_attempt', 'status_of_attempt', 'answer_server', 'newsletter'], 'permissions': [('can_create_mailings', 'Can create mailings'), ('can_view_mailings', 'Can view mailings'), ('can_update_mailings', 'Can update mailings'), ('can_delete_mailings', 'Can delete mailings'), ('can_view_for_manager', 'Can view for manager')], 'verbose_name': 'попытка рассылки', 'verbose_name_plural': 'попытки рассылки'},
        ),
    ]
