# Generated by Django 5.2.4 on 2025-07-19 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('mailings', '0001_initial'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipients',
            new_name='Newsletter',
        ),
    ]
