# Generated by Django 5.2.4 on 2025-07-20 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_rename_recipients_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_of_attempt', models.DateTimeField(auto_now=True)),
                ('status_of_attempt', models.CharField(choices=[('Успешно', 'Успешно'), ('Не успешно', 'Не успешно')], default='Успешно', max_length=100, verbose_name='Статус попытки рассылки')),
                ('answer_server', models.TextField(blank=True, max_length=20, null=True)),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailings.newsletter')),
            ],
            options={
                'ordering': ['dt_of_attempt', 'status_of_attempt', 'answer_server', 'newsletter'],
            },
        ),
    ]
