# Generated by Django 5.2.4 on 2025-07-28 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_alter_mailingattempt_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingattempt',
            options={'ordering': ['dt_of_attempt', 'status_of_attempt', 'answer_server', 'newsletter'], 'permissions': [('can_view_statics', 'Can view statics')], 'verbose_name': 'попытка рассылки', 'verbose_name_plural': 'попытки рассылки'},
        ),
    ]
