# Generated by Django 5.2.4 on 2025-07-23 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_mailingattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingattempt',
            name='dt_of_attempt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
